name: TestDriver.ai Regression Testing
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: 0 21 * * *
  workflow_dispatch: null
  
permissions:
  contents: read  # To allow the action to read repository contents
  pull-requests: write  # To allow the action to create/update pull request comments

jobs:
  test:
    name: TestDriver
    runs-on: ubuntu-latest
    steps:
      - uses: dashcamio/testdriver@main
        id: testdriver
        with:
          prompt: |
            2. click "Continue"
            2. focus the Wave input with the keyboard shortcut Command + I
            3. type 'ls' into the input
            4. press return
            5. validate Wave shows the result of 'ls'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: peter-evans/create-or-update-comment@v4
        if: ${{always()}}
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## TestDriver Summary
            ${{ steps.testdriver.outputs.summary }}
          reactions: |
            +1
            -1